site_name: ESP-IDF Course (by EffessDev)
site_description: Master ESP32 embedded systems with this 100% free course. Zero ads, no paywalls.
site_author: EffessDev
repo_url: https://github.com/effessdev/esp-idf
copyright: >
  Copyright © Faseeh Zaman F S. All rights reserved. Found an issue? <a href="https://github.com/effessdev/esp-idf/issues" style="text-decoration: underline; text-underline-offset: 4px;">Open an issue</a> or <a href="https://github.com/effessdev/esp-idf/pulls" style="text-decoration: underline; text-underline-offset: 4px;">submit a pull request</a> on GitHub. Found this useful? <a href="https://github.com/effessdev/esp-idf" style="text-decoration: underline; text-underline-offset: 4px;">Drop a star</a> to support this project.

theme:
  name: material
  logo: assets/effessdev.svg
  favicon: assets/effessdev.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

nav:
  - Welcome: index.md
  - Getting started:
      - Installation: getting-started/install.md
      - Your first project: getting-started/first-project.md
  - Basics:
      - Blinking an LED: basics/blink.md
      - Hardware interrupts: basics/hardware-interrupts.md
      - Pulse Width Modulation: basics/pwm.md
