site_name: Learn ESP-IDF (by EffessDev)
site_description: Master ESP32 embedded systems. 100% free, zero ads, no paywalls.
site_author: EffessDev
repo_url: https://github.com/effessdev/esp-idf
copyright: >
  Copyright © Faseeh Zaman F S. All rights reserved. • Found an issue? 
  <a href="https://github.com/effessdev/esp-idf/issues" style="text-decoration: underline;">Open an issue</a> 
  or 
  <a href="https://github.com/effessdev/esp-idf/pulls" style="text-decoration: underline;">submit a pull request</a> 
  on GitHub.

theme:
  name: material
  logo: assets/effessdev.svg
  favicon: assets/effessdev.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false

nav:
  - Welcome: index.md
  - Getting started:
      - Installation: 01-getting-started/01-install.md
      - Your first project: 01-getting-started/02-first-project.md
  - Basics:
      - Blinking an LED: 02-basics/01-blink.md
      - Hardware interrupts: 02-basics/02-hardware-interrupts.md
